[CHK-1674] handling new data for transaction details in close payment request
pagopa/pagopa-ecommerce-transactions-service pull request #264
Opened 2023-07-05 15:59 UTC by ciuffagianluca

#### List of Changes

#### Motivation and Context

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-07-05 16:07 UTC, giovanniberti requested changes

2023-07-05 16:07 UTC, giovanniberti commented on pom.xml
> +                    <scmVersion>CHK-1674-add-pspOnUs-flag</scmVersion>
Add dependency on the corresponding PR

2023-07-05 16:07 UTC, giovanniberti commented on src/main/java/it/pagopa/transactions/commands/handlers/TransactionSendClosureHandler.java
> +                    );
This doesn't modify the original object but creates a new one. Is it necessary to split the method call?

2023-07-06 12:37 UTC, giovanniberti commented
Also remember to update API tests if necessary :)

2023-07-06 15:00 UTC, ciuffagianluca commented
Depends on https://github.com/pagopa/pagopa-ecommerce-commons/pull/95

2023-07-11 07:32 UTC, Fernando-Granato commented on src/main/java/it/pagopa/transactions/commands/handlers/TransactionSendClosureHandler.java
> +                        Optional.ofNullable(transactionAuthorizationRequestData).get().getPaymentGateway().name()
why do you check for the correct value of transactionAuthorizationRequestData ? 
```suggestion
                        transactionAuthorizationRequestData.getPaymentGateway().name()
```

2023-07-11 07:34 UTC, Fernando-Granato commented on src/main/java/it/pagopa/transactions/commands/handlers/TransactionSendClosureHandler.java
> +                                ? Optional.ofNullable(transactionAuthorizationCompletedData).get().getErrorCode()
Same for this!

2023-07-11 12:25 UTC, Fernando-Granato commented on src/main/java/it/pagopa/transactions/commands/handlers/TransactionSendClosureHandler.java
> +                        Optional.ofNullable(command.getData()).get().transaction()
Remove this option check?

2023-07-11 12:25 UTC, Fernando-Granato commented on src/main/java/it/pagopa/transactions/commands/handlers/TransactionSendClosureHandler.java
> +                        Optional.ofNullable(command.getData()).get().transaction()
Remove this option check?

2023-07-11 15:07 UTC, Fernando-Granato approved these changes

2023-07-12 07:05 UTC, merged