[CHK-3338] feat: remove old last usage method
pagopa/pagopa-ecommerce-transactions-service pull request #584
Opened 2024-10-15 15:05 UTC by scaminati-bv

#### List of Changes
- remove _pagopa-wallet-usage-update-queue_ connection
- remove queue insertion of _WalletLastUsageEvent_ on _TransactionRequestAuthorization_ handler

#### Motivation and Context
This implementation is not used anymore and is replaced by new last used payment method 

#### How Has This Been Tested?
Unit test

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-10-16 13:35 UTC, pietro-tota submitted a review, later dismissed

2024-10-17 22:25 UTC, ciuffagianluca approved these changes

2024-10-17 22:26 UTC, ciuffagianluca requested changes
Please resolve conflicts

2024-10-24 13:45 UTC, pietro-tota commented on .devops/code-review-pipelines.yml
> +      ref: CHK-3316-align-env
```suggestion
      ref: main
```

2024-10-24 13:46 UTC, pietro-tota submitted a review, later dismissed

2024-10-24 13:46 UTC, ciuffagianluca commented on .devops/code-review-pipelines.yml
> +      ref: CHK-3316-align-env
```suggestion
      ref: main
```

2024-10-24 13:50 UTC, ciuffagianluca approved these changes

2024-10-24 13:50 UTC, scaminati-bv commented on .devops/code-review-pipelines.yml
> +      ref: CHK-3316-align-env
done

2024-10-24 14:15 UTC, merged